"""Self-citation generative model for the Voynich Manuscript.

Implements the Timm-Schinner self-citation hypothesis: the text is generated by
iterative copy/mutate/insert/delete operations on previously written tokens.
An optional positional grammar constraint acts as a selection mechanism.

IMPORTANT: This is an independent reimplementation inspired by the published
description, not the original code. Where the paper's algorithm is ambiguous,
explicit choices are documented in docstrings and surfaced in the Stage Report.
"""
from __future__ import annotations

import collections
import logging
import random
from dataclasses import dataclass

logger = logging.getLogger(__name__)

# Operations applied per new token; probabilities must sum to 1.0
DEFAULT_PARAMS: dict[str, float | str] = {
    "copy_prob": 0.65,
    "mutation_prob": 0.20,
    "insert_prob": 0.10,
    "delete_prob": 0.05,
    "source_weighting": "frequency",  # "uniform" | "frequency" | "recency"
    "grammar_strength": 0.0,          # 0.0 = off, 1.0 = strict rejection
}


@dataclass
class SelfCitationParams:
    copy_prob: float = 0.65
    mutation_prob: float = 0.20
    insert_prob: float = 0.10
    delete_prob: float = 0.05
    source_weighting: str = "frequency"
    grammar_strength: float = 0.0

    def validate(self) -> None:
        total = self.copy_prob + self.mutation_prob + self.insert_prob + self.delete_prob
        if abs(total - 1.0) > 1e-6:
            raise ValueError(f"probabilities must sum to 1.0, got {total}")
        if self.source_weighting not in {"uniform", "frequency", "recency"}:
            raise ValueError(f"unknown source_weighting: {self.source_weighting}")
        if not 0.0 <= self.grammar_strength <= 1.0:
            raise ValueError("grammar_strength must be in [0, 1]")


class SelfCitationGenerator:
    def __init__(
        self,
        seed_corpus: list[list[str]],
        params: SelfCitationParams,
        rng_seed: int = 42,
    ):
        params.validate()
        self.params = params
        self.rng = random.Random(rng_seed)
        self.corpus: list[list[str]] = [list(t) for t in seed_corpus]
        self._glyph_vocab = self._extract_glyph_vocab(seed_corpus)
        self._token_freq = self._compute_token_freq(seed_corpus)
        self._onset_dist, self._coda_dist = self._compute_positional_dists(seed_corpus)

    @staticmethod
    def _extract_glyph_vocab(corpus: list[list[str]]) -> list[str]:
        vocab: collections.Counter[str] = collections.Counter()
        for token in corpus:
            vocab.update(token)
        return list(vocab.keys())

    @staticmethod
    def _compute_token_freq(corpus: list[list[str]]) -> dict[tuple[str, ...], int]:
        freq = collections.Counter(tuple(t) for t in corpus)
        return dict(freq)

    @staticmethod
    def _compute_positional_dists(corpus: list[list[str]]) -> tuple[collections.Counter[str], collections.Counter[str]]:
        onset: collections.Counter[str] = collections.Counter()
        coda: collections.Counter[str] = collections.Counter()
        for token in corpus:
            if not token:
                continue
            onset[token[0]] += 1
            coda[token[-1]] += 1
        return onset, coda

    def _select_source(self) -> list[str]:
        if self.params.source_weighting == "uniform":
            return self.rng.choice(self.corpus)
        if self.params.source_weighting == "frequency":
            keys = [tuple(t) for t in self.corpus]
            weights = [self._token_freq.get(k, 1) for k in keys]
            chosen = self.rng.choices(self.corpus, weights=weights, k=1)[0]
            return chosen
        if self.params.source_weighting == "recency":
            # Weight by position: later tokens more likely
            weights = list(range(1, len(self.corpus) + 1))
            return self.rng.choices(self.corpus, weights=weights, k=1)[0]
        raise ValueError(self.params.source_weighting)

    def _apply_copy(self, source: list[str]) -> list[str]:
        return list(source)

    def _apply_mutate(self, source: list[str]) -> list[str]:
        if not source:
            return [self.rng.choice(self._glyph_vocab)]
        result = list(source)
        idx = self.rng.randrange(len(result))
        # Do not mutate to the same glyph; pick a different one
        choices = [g for g in self._glyph_vocab if g != result[idx]]
        if not choices:
            return result
        result[idx] = self.rng.choice(choices)
        return result

    def _apply_insert(self, source: list[str]) -> list[str]:
        result = list(source)
        idx = self.rng.randrange(len(result) + 1)
        result.insert(idx, self.rng.choice(self._glyph_vocab))
        return result

    def _apply_delete(self, source: list[str]) -> list[str]:
        if len(source) <= 1:
            return list(source)
        result = list(source)
        idx = self.rng.randrange(len(result))
        del result[idx]
        return result

    def _operation(self, source: list[str]) -> list[str]:
        r = self.rng.random()
        p = self.params
        if r < p.copy_prob:
            return self._apply_copy(source)
        r -= p.copy_prob
        if r < p.mutation_prob:
            return self._apply_mutate(source)
        r -= p.mutation_prob
        if r < p.insert_prob:
            return self._apply_insert(source)
        return self._apply_delete(source)

    def _passes_grammar(self, token: list[str]) -> bool:
        """Positional grammar constraint: first and last glyphs must appear in
        the observed onset/coda distributions. With grammar_strength < 1.0,
        rejection is probabilistic."""
        if not token:
            return False
        if self.params.grammar_strength <= 0.0:
            return True
        onset_ok = token[0] in self._onset_dist
        coda_ok = token[-1] in self._coda_dist
        base_ok = onset_ok and coda_ok
        if base_ok:
            return True
        # Probabilistic rejection
        return self.rng.random() >= self.params.grammar_strength

    def generate(self, n_tokens: int, max_attempts_per_token: int = 20) -> list[list[str]]:
        while len(self.corpus) < n_tokens:
            source = self._select_source()
            candidate = self._operation(source)
            if not candidate:
                continue
            # Grammar filter with retries
            attempts = 0
            while not self._passes_grammar(candidate) and attempts < max_attempts_per_token:
                source = self._select_source()
                candidate = self._operation(source)
                attempts += 1
            self.corpus.append(candidate)
        return self.corpus[:n_tokens]


def generate_corpus(
    seed_corpus: list[list[str]],
    n_tokens: int,
    params: SelfCitationParams,
    rng_seed: int = 42,
) -> list[list[str]]:
    """Convenience wrapper. seed_corpus provides the initial corpus and vocab;
    output has exactly n_tokens tokens."""
    gen = SelfCitationGenerator(seed_corpus, params, rng_seed=rng_seed)
    return gen.generate(n_tokens)


if __name__ == "__main__":
    import json

    from src.layer3_mechanisms.data_loader import load_data_bundle
    bundle = load_data_bundle()
    n_tokens = bundle.token_count
    # Use the first 50 observed tokens as the seed
    seed = bundle.tokenized[:50]
    params = SelfCitationParams(
        copy_prob=float(DEFAULT_PARAMS["copy_prob"]),
        mutation_prob=float(DEFAULT_PARAMS["mutation_prob"]),
        insert_prob=float(DEFAULT_PARAMS["insert_prob"]),
        delete_prob=float(DEFAULT_PARAMS["delete_prob"]),
        source_weighting=str(DEFAULT_PARAMS["source_weighting"]),
        grammar_strength=float(DEFAULT_PARAMS["grammar_strength"]),
    )
    out = generate_corpus(seed, n_tokens, params)
    print(json.dumps({"n_generated": len(out), "first_5": out[:5]}, default=str, indent=2))